---

- name: ensure openssh-server is present
  ansible.builtin.apt:
    pkg: openssh-server
    state: present
    install_recommends: no
    force: yes
    cache_valid_time: 3600
  notify: restart sshd

- name: ensure host keys are present
  ansible.builtin.command: "ssh-keygen -q -f ssh_host_{{ item }}_key -N '' -t {{ item }}"
  args:
    chdir: /etc/ssh
    creates: "/etc/ssh/ssh_host_{{ item }}_key"
  loop: "{{ sshd_host_keys }}"

- name: ensure openssh config is latest
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart sshd

- name: ensure sftp chroot group is present
  ansible.builtin.group:
    name: "{{ sshd_sftp_chroot_group }}"
  when: sshd_sftp_chroot == 'yes'

- name: ensure /run/sshd exists (for containers)
  ansible.builtin.file:
    path: /run/sshd
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: check sshd config
  ansible.builtin.command: /usr/sbin/sshd -t
  register: __sshd_check_config
  changed_when: False
  failed_when: __sshd_check_config.stderr

- name: include task for authorized_keys
  ansible.builtin.import_tasks: authorized_keys.yml
  when: sshd_authorized_keys_file == "/etc/ssh/authorized_keys/%u"

- name: include task for goss 
  ansible.builtin.import_tasks: goss.yml
  tags:
    - goss
